backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "tours"
    label: "Tours"
    folder: "content/tours"
    create: true
    fields:
      - { name: "title", label: "Заголовок", widget: "string" }
      - { name: "description", label: "Описание", widget: "text" }
      - { name: "price", label: "Цена", widget: "string" }
      - { name: "image", label: "Изображение", widget: "image" }
      - { name: "date", label: "Дата", widget: "datetime" }
