backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Создан тур: {{slug}}"
    update: "Обновлён тур: {{slug}}"

media_folder: "static/img"    # Путь для сохранения изображений
public_folder: "/img"         # Публичный путь к изображениям

collections:
  - name: "tours"
    label: "Туры"
    folder: "content/tours"   # Путь к файлам туров
    create: true
    slug: "{{fields.title}}"
    fields:
      - { name: "title", label: "Название", widget: "string" }
      - { name: "description", label: "Описание", widget: "markdown" }
      - { name: "price", label: "Цена", widget: "string" }
      - { name: "date", label: "Дата", widget: "datetime" }
      - { name: "image", label: "Изображение", widget: "image" }
