backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"      # куда сохраняются изображения
public_folder: "/images/uploads"    # как отображаются изображения на сайте

collections:
  - name: "tours"
    label: "Туры"
    folder: "content/tours"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название тура", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "text" }
      - { label: "Дата начала", name: "start_date", widget: "datetime" }
      - { label: "Фото", name: "image", widget: "image" }

  - name: "reviews"
    label: "Отзывы"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Имя", name: "author", widget: "string" }
      - { label: "Текст отзыва", name: "body", widget: "text" }
      - { label: "Дата", name: "date", widget: "datetime" }
